# Generated by Django 4.1 on 2022-08-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
